name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push frontend image
        run: |
            docker buildx build --platform linux/amd64 \
            --tag ${{ secrets.DOCKER_USERNAME }}/qr-gen-frontend:latest \
            --push \
            front-end-nextjs

      - name: Build and push backend image
        run: |
            docker buildx build --platform linux/amd64 \
            --tag ${{ secrets.DOCKER_USERNAME }}/qr-gen-backend:latest \
            --push \
            api

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Run SSH command
        uses: garygrossgarten/github-action-ssh@0.8.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          command: | 
              cd ~/git-repos/devops-qr-code \
              && git pull --rebase \
              && docker compose down \
              && docker compose -f docker-compose.yaml up -d --build
